version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - mvn clean test package
      - cp target/cicddemo.jar cicddemo.jar

artifacts:
  files:
    - cicddemo.jar
    - Procfile